"""API 文档页 ``/docs``（服务端渲染，中英双语）。

设计取舍
--------
* **服务端渲染而非前端 SPA**：本页是给开发者读的参考文档，``curl /docs`` 与
  浏览器「查看源代码」都应看到完整内容；同时继承本项目「零外部依赖」的取向，
  ``/docs`` 不加载任何 JS（无 i18n.js），语言由请求参数决定（``?lang=en|zh``）。
* **清单即事实来源**：:data:`ENDPOINTS` 是全部路由的唯一登记处，改路由时同步改这里，
  页面自动呈现。与 ``src/web.py`` 的路由表互为镜像，``tests/test_web.py`` 会做一致性校验，
  避免文档与实现漂移。
"""
from __future__ import annotations

#: 端点清单。``auth=True`` 表示管理端点（生产环境需 ``X-Admin-Token`` 或 ``?token=``）。
#: ``group`` 取值见 :data:`GROUPS` 的键。
ENDPOINTS: list[dict[str, object]] = [
    # ── 页面与静态资源 ────────────────────────────────────────────────
    {
        "group": "pages", "method": "GET", "path": "/", "auth": False,
        "title": ("落地页", "Landing page"),
        "desc": ("产品介绍、能力说明与数据源声明，首屏统计数字由 ``/api/stats`` 实时填充。",
                 "Product overview, capabilities and data-source statement. The headline "
                 "counters are filled at runtime from ``/api/stats``."),
        "params": [
            {"name": "lang", "type": "en | zh", "required": False,
             "d": ("决定 ``<html lang>`` 与分享卡片语言；缺省按 ``Accept-Language``，"
                   "再退回 ``en``。",
                   "Controls ``<html lang>`` and the share card. Falls back to "
                   "``Accept-Language``, then ``en``.")},
        ],
        "example": "curl -s \"$BASE/?lang=en\"",
    },
    {
        "group": "pages", "method": "GET", "path": "/app", "auth": False,
        "title": ("数据看板", "Data dashboard"),
        "desc": ("看板主界面：智能查询、指标总表、自定义分析、统计公报、图表五个工作台。",
                 "Dashboard: AI query, indicator table, custom analysis, statistical "
                 "bulletin and charts."),
        "params": [
            {"name": "lang", "type": "en | zh", "required": False,
             "d": ("界面语言占位符 ``__HTML_LANG__`` 的取值来源。",
                   "Source of the ``__HTML_LANG__`` placeholder.")},
        ],
        "example": "curl -s \"$BASE/app?lang=zh\"",
    },
    {
        "group": "pages", "method": "GET", "path": "/docs", "auth": False,
        "title": ("本页", "This page"),
        "desc": ("API 参考。内容按 ``?lang=`` 服务端渲染，无需 JavaScript。",
                 "The API reference. Rendered server-side per ``?lang=``, no JavaScript "
                 "required."),
        "params": [
            {"name": "lang", "type": "en | zh", "required": False,
             "d": ("文档语言。", "Documentation language.")},
        ],
        "example": "curl -s \"$BASE/docs?lang=en\" | less",
    },
    {
        "group": "pages", "method": "GET", "path": "/privacy", "auth": False,
        "title": ("隐私与数据声明", "Privacy & data statement"),
        "desc": ("对外分发后最常被问的三件事（收集什么 / 数据从哪来 / AI 会不会把问题发出去）"
                 "的固定答案。同样服务端渲染、零 JS。",
                 "The standing answer to the three questions asked most often after going "
                 "public: what is collected, where the data comes from, and whether the AI "
                 "sends your question anywhere. Also server-rendered, zero JS."),
        "params": [
            {"name": "lang", "type": "en | zh", "required": False,
             "d": ("声明语言。", "Statement language.")},
        ],
        "example": "curl -s \"$BASE/privacy?lang=en\"",
    },
    {
        "group": "pages", "method": "GET", "path": "/theme.css · /style.css · /app.js · /i18n.js",
        "auth": False,
        "title": ("前端资源", "Frontend assets"),
        "desc": ("四份前端资源（主题令牌 / 样式 / 逻辑 / 词表）。页面引用时带内容哈希版本号 "
                 "``?v=<sha256 前 12 位>``，因此可以放心长缓存。",
                 "The three frontend assets (styles / logic / word list). Pages reference "
                 "them with a content-hash version, ``?v=<sha256[:12]>``, which makes the "
                 "long cache safe."),
        "params": [],
        "example": "curl -sI \"$BASE/style.css\" | grep -i cache-control",
    },
    {
        "group": "pages", "method": "GET", "path": "/og-image.png · /favicon.svg",
        "auth": False,
        "title": ("图标与分享卡片", "Icon & share card"),
        "desc": ("``og-image.png`` 为 1200×630 社交分享卡片（由 ``scripts/make_og_image.py`` "
                 "生成后 base64 内嵌，见 ``src/pages.py``）。",
                 "``og-image.png`` is the 1200×630 social share card, generated by "
                 "``scripts/make_og_image.py`` and embedded as base64 in ``src/pages.py``."),
        "params": [],
        "example": "curl -sI \"$BASE/og-image.png\" | grep -i content-type",
    },
    {
        "group": "pages", "method": "GET", "path": "/robots.txt · /sitemap.xml",
        "auth": False,
        "title": ("SEO 资源", "SEO resources"),
        "desc": ("爬虫协议与站点地图，缓存 1 小时。",
                 "Crawler policy and sitemap, cached for one hour."),
        "params": [],
        "example": "curl -s \"$BASE/robots.txt\"",
    },

    # ── 数据接口 ──────────────────────────────────────────────────────
    {
        "group": "data", "method": "GET", "path": "/api/stats", "auth": False,
        "title": ("数据规模", "Dataset size"),
        "desc": ("公开只读的聚合计数（记录数、知识条目数、覆盖经济体与年份），供落地页"
                 "与看板侧栏展示。**不含**库路径等环境细节——那些在管理端点 ``/api/db``。",
                 "Public read-only aggregate counts (rows, knowledge entries, covered "
                 "economies and years) for the landing page and dashboard sidebar. Contains "
                 "**no** environment details such as DB paths — those live in ``/api/db``."),
        "params": [],
        "example": "curl -s \"$BASE/api/stats\"",
    },
    {
        "group": "data", "method": "GET", "path": "/api/overview", "auth": False,
        "title": ("概览卡片", "Overview cards"),
        "desc": ("按年份 + 维度返回关键指标卡片，每张卡片含本地化展示值、``*_key``"
                 "（中文规范键）与 ``*_slug``（ASCII 稳定键）；同时返回下拉框可选项。",
                 "Returns the headline cards for a year + dimension. Each card carries the "
                 "localized display value plus ``*_key`` (canonical Chinese key) and "
                 "``*_slug`` (stable ASCII key). Dropdown options are included."),
        "params": [
            {"name": "year", "type": "int", "required": False,
             "d": ("年份，缺省 2024。", "Year, defaults to 2024.")},
            {"name": "dimension", "type": "str", "required": False,
             "d": ("经济体：接受规范键（``中国``）、英文标签（``China``）或 slug（``china``）；"
                   "缺省 ``亚太`` 聚合口径。",
                   "Economy: accepts the canonical key (``中国``), the English label "
                   "(``China``) or the slug (``china``). Defaults to the ``亚太`` aggregate.")},
            {"name": "lang", "type": "en | zh", "required": False,
             "d": ("本地化语言。", "Localization language.")},
        ],
        "example": "curl -s \"$BASE/api/overview?year=2024&dimension=china&lang=en\"",
    },
    {
        "group": "data", "method": "GET", "path": "/api/insights", "auth": False,
        "title": ("数据洞察", "Data insights"),
        "desc": ("从本地公开数据算出**可复算**的年度变化：该维度同比变化最大的指标、"
                 "覆盖最广指标上名次变动最大的经济体，以及本年度真实覆盖规模。"
                 "每条洞察都带两年数值，可用 ``/api/indicators`` 复核；上一年缺失或为 0 "
                 "的指标不进榜单，不给误导性百分比。",
                 "Recomputable year-over-year movements computed from local public data: "
                 "the biggest movers for the dimension, the economies with the largest "
                 "rank changes on the widest-coverage indicator, and the real coverage "
                 "counts. Every item carries both year values so it can be checked "
                 "against ``/api/indicators``; indicators without a prior-year value "
                 "are omitted rather than given a misleading percentage."),
        "params": [
            {"name": "year", "type": "int", "required": False,
             "d": ("年份，缺省 2024。洞察为「当年 vs 上一年」。",
                   "Year, defaults to 2024. Insights compare it with the prior year.")},
            {"name": "dimension", "type": "str", "required": False,
             "d": ("经济体：接受规范键、英文标签或 slug；缺省 ``亚太`` 聚合口径。",
                   "Economy: canonical key, English label or slug; defaults to the "
                   "``亚太`` aggregate.")},
            {"name": "lang", "type": "en | zh", "required": False,
             "d": ("本地化语言。", "Localization language.")},
        ],
        "example": "curl -s \"$BASE/api/insights?year=2024&dimension=china&lang=en\"",
    },
    {
        "group": "data", "method": "GET", "path": "/api/indicators", "auth": False,
        "title": ("指标宽表", "Indicator wide table"),
        "desc": ("面向程序消费的主要数据接口。每行的 ``category`` / ``indicator`` / "
                 "``dimension`` / ``unit`` 按 ``lang`` 本地化，并并列给出 ``*_key`` 与 "
                 "``*_slug``——英文消费方无需任何中文词表即可使用。",
                 "The primary machine-readable endpoint. ``category`` / ``indicator`` / "
                 "``dimension`` / ``unit`` are localized per ``lang``, each accompanied by "
                 "``*_key`` and ``*_slug``, so English consumers need no Chinese glossary."),
        "params": [
            {"name": "year", "type": "int", "required": False,
             "d": ("缺省表示跨年全量。", "Omit for every year.")},
            {"name": "dimension", "type": "str", "required": False,
             "d": ("经济体（键 / 标签 / slug 皆可）。", "Economy (key / label / slug).")},
            {"name": "category", "type": "str", "required": False,
             "d": ("专业分类。", "Profession / category.")},
            {"name": "indicator", "type": "str", "required": False,
             "d": ("指标名（键 / 标签 / slug 皆可）。", "Indicator (key / label / slug).")},
            {"name": "q", "type": "str", "required": False,
             "d": ("模糊搜索：同时匹配原始行与本地化行的全部字段（中英文均命中）。",
                   "Free-text search across both the raw and the localized row, in either "
                   "language.")},
            {"name": "lang", "type": "en | zh", "required": False,
             "d": ("本地化语言。", "Localization language.")},
        ],
        "example": ("curl -s \"$BASE/api/indicators?indicator=GDP&year=2024&lang=en\"\n"
                    "# 或按关键词搜索（中英均可）\n"
                    "curl -s \"$BASE/api/indicators?q=retail\" | head -40"),
    },
    {
        "group": "data", "method": "GET", "path": "/api/export.csv", "auth": False,
        "title": ("CSV 导出", "CSV export"),
        "desc": ("把当前筛选结果导出为 CSV。列固定为 "
                 "``year,category,indicator,dimension,value,unit,note``，内容带 BOM"
                 "（``utf-8-sig``）以便 Excel 直接打开；文件名含年份、维度 slug 与语言。",
                 "Exports the current selection as CSV with the fixed columns "
                 "``year,category,indicator,dimension,value,unit,note``. Content is BOM-prefixed "
                 "(``utf-8-sig``) so Excel opens it directly; the filename encodes year, "
                 "dimension slug and language."),
        "params": [
            {"name": "year · dimension · indicator · category · q · lang",
             "type": "—", "required": False,
             "d": ("与 ``/api/indicators`` 完全一致。",
                   "Identical to ``/api/indicators``.")},
        ],
        "example": ("curl -s \"$BASE/api/export.csv?year=2024&dimension=china&lang=en\" \\\n"
                    "  -o indicators_2024_china_en.csv"),
    },
    {
        "group": "data", "method": "GET", "path": "/api/indicator_keys", "auth": False,
        "title": ("可绑定指标键", "Bindable indicator keys"),
        "desc": ("返回全部可绑定指标的三元组（专业 / 指标 / 维度），供「新建自定义分析」的"
                 "变量下拉选择使用。",
                 "Returns every bindable (category, indicator, dimension) triple for the "
                 "custom-analysis variable pickers."),
        "params": [
            {"name": "lang", "type": "en | zh", "required": False,
             "d": ("本地化语言。", "Localization language.")},
        ],
        "example": "curl -s \"$BASE/api/indicator_keys?lang=en\"",
    },
    {
        "group": "data", "method": "GET", "path": "/api/custom", "auth": False,
        "title": ("自定义分析（查询）", "Custom analyses (read)"),
        "desc": ("不带 ``name`` 时返回分析列表（含中英名称）；带 ``name`` 时求值并返回结果，"
                 "``compare`` 为真时附同比 ``yoy``。名称中英皆可命中。",
                 "Without ``name`` it lists the analyses (with both language names). With "
                 "``name`` it evaluates one and returns the result; ``compare`` analyses also "
                 "carry a ``yoy`` value. The name matches in either language."),
        "params": [
            {"name": "name", "type": "str", "required": False,
             "d": ("分析名称；缺省列出全部。", "Analysis name; omit to list all.")},
            {"name": "year", "type": "int", "required": False,
             "d": ("求值年份，缺省 2024。", "Evaluation year, defaults to 2024.")},
            {"name": "lang", "type": "en | zh", "required": False,
             "d": ("本地化语言。", "Localization language.")},
        ],
        "example": "curl -s \"$BASE/api/custom?name=GDP&lang=en\"",
    },
    {
        "group": "data", "method": "POST", "path": "/api/custom", "auth": False,
        "title": ("自定义分析（新增）", "Custom analyses (create)"),
        "desc": ("追加一条分析到配置文件。表达式在**占位值**上预校验可求值，且不允许重复"
                 "名称；变量取值失败时返回 ``error`` 字段而不抛异常。",
                 "Appends an analysis to the config file. The expression is pre-validated "
                 "against placeholder values and duplicate names are rejected. A variable "
                 "that cannot resolve yields an ``error`` field rather than an exception."),
        "params": [],
        "body": (
            "JSON 请求体：\n"
            "{\n"
            '  "name": "第三产业占比",          // 必填，中文规范名\n'
            '  "name_en": "Tertiary share",      // 可选，英文展示名\n'
            '  "unit": "%",\n'
            '  "description": "…",\n'
            '  "description_en": "…",\n'
            '  "variables": {                    // 必填，变量名 -> [专业, 指标, 维度(可选)]\n'
            '    "x": ["国民经济", "第三产业增加值", "中国"],\n'
            '    "y": ["国民经济", "GDP", "中国"]\n'
            "  },\n"
            '  "expr": "x / y * 100",            // 必填，安全求值\n'
            '  "compare": true                   // 可选，是否计算同比\n'
            "}",
            "JSON body:\n"
            "{\n"
            '  "name": "Tertiary share",        // required, canonical name\n'
            '  "name_en": "Tertiary share",      // optional display name\n'
            '  "unit": "%",\n'
            '  "description": "…",\n'
            '  "description_en": "…",\n'
            '  "variables": {                    // required: var -> [category, indicator, dimension?]\n'
            '    "x": ["国民经济", "第三产业增加值", "中国"],\n'
            '    "y": ["国民经济", "GDP", "中国"]\n'
            "  },\n"
            '  "expr": "x / y * 100",            // required, safely evaluated\n'
            '  "compare": true                   // optional, compute YoY\n'
            "}"),
        "example": ("curl -s -X POST \"$BASE/api/custom\" \\\n"
                    "  -H 'Content-Type: application/json' \\\n"
                    "  -d '{\"name\":\"Tertiary share\",\"variables\":{\"x\":[\"国民经济\","
                    "\"第三产业增加值\",\"中国\"]},\"expr\":\"x\"}'"),
    },
    {
        "group": "data", "method": "GET", "path": "/api/report", "auth": False,
        "title": ("统计公报", "Statistical bulletin"),
        "desc": ("按年份 + 维度生成公报。``format=json`` 返回结构化数据（标识符已由服务端"
                 "本地化，交前端渲染）；缺省返回纯文本 Markdown。``cloud=1`` 时附云端 AI 解读。",
                 "Generates a bulletin for a year + dimension. ``format=json`` returns "
                 "structured data (identifiers already localized server-side) for the frontend "
                 "to render; the default is plain-text Markdown. ``cloud=1`` adds a cloud AI "
                 "interpretation."),
        "params": [
            {"name": "year", "type": "int", "required": False,
             "d": ("缺省 2024。", "Defaults to 2024.")},
            {"name": "dimension", "type": "str", "required": False,
             "d": ("经济体，缺省 ``亚太``。", "Economy, defaults to ``亚太``.")},
            {"name": "cloud", "type": "0 | 1", "required": False,
             "d": ("是否请求云端 AI 解读。", "Whether to request the cloud AI interpretation.")},
            {"name": "format", "type": "json", "required": False,
             "d": ("出现即为 JSON，否则文本。", "Present → JSON, otherwise plain text.")},
            {"name": "lang", "type": "en | zh", "required": False,
             "d": ("本地化语言。", "Localization language.")},
        ],
        "example": "curl -s \"$BASE/api/report?year=2024&format=json&lang=en\"",
    },

    # ── 解读接口 ──────────────────────────────────────────────────────
    {
        "group": "ai", "method": "GET", "path": "/api/ask", "auth": False,
        "title": ("自然语言查询", "Natural-language query"),
        "desc": ("把一句自然语言问题解析为指标查询并返回统计结果。``cloud=1`` 时，**本地"
                 "统计结果先作为事实上下文**再交给云端模型（提示词中明确要求只依据给定数字），"
                 "避免模型编造数据；云端不可用时退回本地统计并在 ``注`` 字段说明。",
                 "Parses a natural-language question into indicator queries. With ``cloud=1`` "
                 "the **local statistics are passed to the model as grounding facts** (the "
                 "prompt forbids inventing figures). If the cloud is unavailable it degrades "
                 "to local statistics and explains that in the ``注`` field."),
        "params": [
            {"name": "text", "type": "str", "required": True,
             "d": ("自然语言问题，如 ``2024年GDP`` 或 ``retail sales``。",
                   "The question, e.g. ``2024 GDP`` or ``retail sales``.")},
            {"name": "dimension", "type": "str", "required": False,
             "d": ("限定经济体。", "Restrict to one economy.")},
            {"name": "cloud", "type": "0 | 1", "required": False,
             "d": ("是否调用云端 AI 解读。", "Call the cloud AI interpretation or not.")},
            {"name": "lang", "type": "en | zh", "required": False,
             "d": ("本地化语言（同时决定云端提示词语言）。",
                   "Localization language; also selects the cloud prompt language.")},
        ],
        "example": "curl -s \"$BASE/api/ask?text=2024%20GDP&lang=en&cloud=0\"",
    },

    {
        "group": "ai", "method": "GET", "path": "/api/infini_skill", "auth": False,
        "title": ("集成自检", "Integration self-check"),
        "desc": ("按 agent_infini Skill 规范返回推荐工作流与资源预检结果；只读、不触发"
                 "任何云端调用，CLI 不可用时优雅降级。",
                 "Returns the recommended agent_infini workflow and a resource "
                 "pre-flight result. Read-only; never triggers a cloud call, and "
                 "degrades gracefully when the CLI is absent."),
        "params": [
            {"name": "db", "type": "str", "required": False,
             "d": ("逗号分隔的数据库标识，用于核验是否已启用。",
                   "Comma-separated database ids to verify.")},
            {"name": "rag", "type": "str", "required": False,
             "d": ("逗号分隔的 RAG 知识库标识，用于核验是否已启用。",
                   "Comma-separated RAG knowledge-base ids to verify.")},
        ],
        "example": "curl -s \"$BASE/api/infini_skill\"",
    },
    {
        "group": "ai", "method": "GET", "path": "/api/ai-cache", "auth": False,
        "title": ("解读缓存指标", "Interpretation cache metrics"),
        "desc": ("AI 解读缓存的运行指标：命中 / 未命中计数、L1 容量、Redis 是否可用。"
                 "只读、无副作用，用来验证「重复提问真的没有重复打云端」。",
                 "Runtime metrics for the interpretation cache: hit / miss counters, "
                 "L1 capacity and whether Redis is available. Read-only and "
                 "side-effect free — it proves a repeated question never re-hit the "
                 "cloud."),
        "params": [],
        "example": "curl -s \"$BASE/api/ai-cache\"",
    },

    # ── 知识库接口 ────────────────────────────────────────────────────
    {
        "group": "kb", "method": "GET", "path": "/api/knowledge", "auth": False,
        "title": ("知识库（查询）", "Knowledge base (read)"),
        "desc": ("列出或搜索知识条目；命中结果会作为本地统计的补充上下文出现在问答结果中。",
                 "Lists or searches knowledge entries; matches are attached to query answers "
                 "as supplementary context."),
        "params": [
            {"name": "q", "type": "str", "required": False,
             "d": ("关键词搜索；缺省列出全部。", "Keyword search; omit to list all.")},
            {"name": "category", "type": "str", "required": False,
             "d": ("按分类过滤。", "Filter by category.")},
        ],
        "example": "curl -s \"$BASE/api/knowledge?q=GDP\"",
    },
    {
        "group": "kb", "method": "POST", "path": "/api/knowledge", "auth": False,
        "title": ("知识库（新增）", "Knowledge base (create)"),
        "desc": ("新增一条知识条目，``title`` 与 ``content`` 必填。",
                 "Adds an entry; ``title`` and ``content`` are required."),
        "params": [],
        "body": ('JSON 请求体：{"title": "…", "content": "…", "category": "通用", '
                 '"tags": "gdp,trade", "source": "…"}',
                 'JSON body: {"title": "…", "content": "…", "category": "通用", '
                 '"tags": "gdp,trade", "source": "…"}'),
        "example": ("curl -s -X POST \"$BASE/api/knowledge\" \\\n"
                    "  -H 'Content-Type: application/json' \\\n"
                    "  -d '{\"title\":\"GDP 口径\",\"content\":\"…\"}'"),
    },
    {
        "group": "kb", "method": "DELETE", "path": "/api/knowledge", "auth": False,
        "title": ("知识库（删除）", "Knowledge base (delete)"),
        "desc": ("按 ``id`` 删除条目。", "Deletes an entry by ``id``."),
        "params": [
            {"name": "id", "type": "int", "required": True,
             "d": ("条目 ID。", "Entry id.")},
        ],
        "example": "curl -s -X DELETE \"$BASE/api/knowledge?id=1\"",
    },

    # ── 管理接口 ──────────────────────────────────────────────────────
    {
        "group": "admin", "method": "GET", "path": "/api/db", "auth": True,
        "title": ("库状态", "Database status"),
        "desc": ("返回数据库路径、引擎、体积与各表行数。**含环境细节**，故列入管理端点。",
                 "Returns the DB path, engine, size and per-table row counts. It **exposes "
                 "environment details**, hence admin-only."),
        "params": [],
        "example": "curl -s \"$BASE/api/db\" -H \"X-Admin-Token: $ADMIN_TOKEN\"",
    },
    {
        "group": "admin", "method": "POST", "path": "/api/reseed", "auth": True,
        "title": ("重新播种", "Re-seed"),
        "desc": ("清空指标表后重新载入内嵌的真实公开数据种子集，并清除 KV 旧快照。"
                 "**会覆盖库内数据**。",
                 "Truncates the indicators table and reloads the embedded public-data seed "
                 "set, clearing the stale KV snapshot. **Overwrites existing rows.**"),
        "params": [],
        "example": "curl -s -X POST \"$BASE/api/reseed\" -H \"X-Admin-Token: $ADMIN_TOKEN\"",
    },
    {
        "group": "admin", "method": "GET", "path": "/api/kv-status", "auth": True,
        "title": ("KV 状态", "KV status"),
        "desc": ("检查 Redis / Vercel KV 持久化连接：环境变量存在性（已脱敏）、写入与回读。",
                 "Checks the Redis / Vercel KV connection: env-var presence (masked), write "
                 "and read-back."),
        "params": [],
        "example": "curl -s \"$BASE/api/kv-status\" -H \"X-Admin-Token: $ADMIN_TOKEN\"",
    },
    {
        "group": "admin", "method": "POST", "path": "/api/collect", "auth": True,
        "title": ("数据采集", "Data collection"),
        "desc": ("从世界银行 Open Data 拉取指定指标并入库（公开数据源，无需鉴权）。"
                 "需要可写磁盘，故线上默认关闭。",
                 "Fetches indicators from World Bank Open Data and stores them (public "
                 "source, no auth). Requires a writable disk, so it is off in production."),
        "params": [],
        "body": ('JSON 请求体：{"source": "worldbank" | "global", "year": 2024, '
                 '"country": "CN", "indicators": "NY.GDP.MKTP.CD"}',
                 'JSON body: {"source": "worldbank" | "global", "year": 2024, '
                 '"country": "CN", "indicators": "NY.GDP.MKTP.CD"}'),
        "example": ("curl -s -X POST \"$BASE/api/collect\" \\\n"
                    "  -H 'Content-Type: application/json' -H \"X-Admin-Token: $ADMIN_TOKEN\" \\\n"
                    "  -d '{\"source\":\"worldbank\",\"year\":2024,"
                    "\"indicators\":\"NY.GDP.MKTP.CD\"}'"),
    },
]

#: 分组元数据（顺序即页面顺序）。
GROUPS: dict[str, tuple[str, str]] = {
    "pages": ("页面与静态资源", "Pages & static assets"),
    "data": ("数据接口", "Data endpoints"),
    "ai": ("解读接口", "Interpretation"),
    "kb": ("知识库接口", "Knowledge base"),
    "admin": ("管理接口（需令牌）", "Admin endpoints (token required)"),
}

_ZH = {
    "doc.title": "API 参考 · 亚太统计分析系统",
    "doc.h1": "API 参考",
    "doc.lead": ("亚太统计分析系统的 REST 接口。全部数据来自公开来源"
                 "（世界银行 Open Data · 中国国家统计局 · 中国海关总署），"
                 "标识符在服务端按请求语言本地化。"),
    "doc.base": "Base URL",
    "doc.auth": "鉴权",
    "doc.auth.v": "公开端点无需鉴权；管理端点需 X-Admin-Token 或 ?token=",
    "doc.format": "响应格式",
    "doc.format.v": "JSON / CSV / Markdown（按端点）",
    "doc.cache": "缓存",
    "doc.cache.v": "接口与 HTML no-store；静态资源 1 年 immutable（URL 带内容哈希）",
    "toc": "本页目录",
    "sec.conv": "通用约定",
    "sec.eps": "接口一览",
    "conv.lang.h": "语言参数 lang",
    "conv.lang.b": ("``?lang=en|zh`` 优先；缺省读 ``Accept-Language``，再退回 ``en``（与产品"
                    "默认语言一致）。页面 ``<html lang>`` 与分享卡片语言同源。"),
    "conv.id.h": "标识符的三把键",
    "conv.id.b": ("数据表里存的是**中文规范键**，本地化只发生在服务端一处。每条记录同时给出："
                  "``field``（当前语言的展示值）、``field_key``（中文规范键）、"
                  "``field_slug``（ASCII 稳定键）。请求参数接受三者任一，因此英文调用方"
                  "不必维护任何中文词表。"),
    "conv.unknown.h": "未登记词条原样返回",
    "conv.unknown.b": ("标签包未收录的词条按原文返回，**不抛异常**——向前兼容新增数据。"
                       "反过来，无法解析的维度（如 ``?dimension=Atlantis``）也原样透传后"
                       "查不到数据，不会静默替换为默认值。"),
    "conv.err.h": "错误约定",
    "conv.err.b": ("校验失败返回 ``{\"ok\": false, \"error\": \"…\"}`` 并带 400；"
                   "鉴权失败 403；找不到 404；上游数据源失败 502。错误文案按 ``lang`` 本地化。"),
    "conv.sec.h": "安全响应头",
    "conv.sec.b": ("所有响应带 ``X-Content-Type-Options: nosniff``、``X-Frame-Options: SAMEORIGIN``、"
                   "``Referrer-Policy: strict-origin-when-cross-origin``、``Permissions-Policy`` "
                   "与收敛到 ``'self'`` 的 CSP；HTTPS 下追加 HSTS。项目**零外部 CDN 依赖**"
                   "（字体走系统字体栈）。"),
    "conv.data.h": "数据来源与许可",
    "conv.data.b": ("世界银行 Open Data（CC BY 4.0 公共许可）、中国国家统计局与中国海关总署"
                    "公开发布物。本项目**仅使用公开数据**，不含任何内部或涉密数据。"),
    "th.param": "参数",
    "th.type": "类型",
    "th.req": "必填",
    "th.desc": "说明",
    "req.yes": "是",
    "req.no": "否",
    "no.params": "无请求参数。",
    "label.example": "示例",
    "label.body": "请求体",
    "badge.public": "公开",
    "badge.admin": "需管理令牌",
    "admin.note": ("管理端点未配置 ``QU_STAT_ADMIN_TOKEN`` 时：本地开发放行，"
                   "部署到 Vercel 一律 403（无持久盘，重播种 / 抓取也无处落库）。"),
    "footer": "亚太统计分析系统 · 仅使用官方公开数据",
    "back.home": "返回落地页",
    "back.app": "进入数据看板",
    "privacy.link": "隐私与数据声明",
}

_EN = {
    "doc.title": "API Reference · Asia-Pacific Statistical Analysis System",
    "doc.h1": "API Reference",
    "doc.lead": ("REST interface of the Asia-Pacific Statistical Analysis System. Every "
                 "figure comes from official public sources (World Bank Open Data · China NBS "
                 "· China Customs); identifiers are localized server-side per request."),
    "doc.base": "Base URL",
    "doc.auth": "Auth",
    "doc.auth.v": "Public endpoints need none; admin endpoints need X-Admin-Token or ?token=",
    "doc.format": "Format",
    "doc.format.v": "JSON / CSV / Markdown (per endpoint)",
    "doc.cache": "Caching",
    "doc.cache.v": "API and HTML are no-store; static assets are immutable for 1 year (URLs carry a content hash)",
    "toc": "On this page",
    "sec.conv": "Conventions",
    "sec.eps": "Endpoints",
    "conv.lang.h": "The lang parameter",
    "conv.lang.b": ("``?lang=en|zh`` wins; otherwise ``Accept-Language`` is read, then ``en`` "
                    "(the product default). The page's ``<html lang>`` and the share card "
                    "derive from the same value."),
    "conv.id.h": "Three keys per identifier",
    "conv.id.b": ("The data tables store **canonical Chinese keys**; localization happens in "
                  "exactly one place, server-side. Every record exposes ``field`` (display "
                  "value in the requested language), ``field_key`` (canonical key) and "
                  "``field_slug`` (stable ASCII key). Request parameters accept any of the "
                  "three, so English consumers need no Chinese glossary."),
    "conv.unknown.h": "Unknown terms pass through",
    "conv.unknown.b": ("Terms missing from the label pack are returned verbatim rather than "
                       "raising — new data stays forward-compatible. Likewise an unresolvable "
                       "dimension such as ``?dimension=Atlantis`` is passed through and simply "
                       "matches nothing; it is never silently swapped for a default."),
    "conv.err.h": "Errors",
    "conv.err.b": ("Validation failures return ``{\"ok\": false, \"error\": \"…\"}`` with 400; "
                   "403 for auth, 404 when missing, 502 when an upstream source fails. Error "
                   "text is localized per ``lang``."),
    "conv.sec.h": "Security headers",
    "conv.sec.b": ("Every response carries ``X-Content-Type-Options: nosniff``, "
                   "``X-Frame-Options: SAMEORIGIN``, "
                   "``Referrer-Policy: strict-origin-when-cross-origin``, a restrictive "
                   "``Permissions-Policy`` and a CSP locked to ``'self'``; HSTS is added over "
                   "HTTPS. The project has **zero external CDN dependencies** (fonts use the "
                   "system stack)."),
    "conv.data.h": "Sources & license",
    "conv.data.b": ("World Bank Open Data (CC BY 4.0), plus public releases from China NBS "
                    "and China Customs. This project uses **only public data** — no internal "
                    "or restricted material."),
    "th.param": "Parameter",
    "th.type": "Type",
    "th.req": "Required",
    "th.desc": "Description",
    "req.yes": "yes",
    "req.no": "no",
    "no.params": "No parameters.",
    "label.example": "Example",
    "label.body": "Request body",
    "badge.public": "Public",
    "badge.admin": "Admin token",
    "admin.note": ("With no ``QU_STAT_ADMIN_TOKEN`` configured, admin endpoints are permitted "
                   "in local development and return 403 on Vercel — there is no persistent "
                   "disk, so re-seeding or collecting has nowhere to land."),
    "footer": "Asia-Pacific Statistical Analysis System · official public data only",
    "back.home": "Back to landing page",
    "back.app": "Open the dashboard",
    "privacy.link": "Privacy & data",
}

_CSS = """
* { box-sizing: border-box; }
body { margin: 0; background: var(--surface); color: var(--gray-700); }
a { color: var(--blue-600); }
code { font-family: var(--mono); font-size: .86em; }
.docs-nav {
  position: sticky; top: 0; z-index: 20;
  display: flex; align-items: center; gap: 16px;
  padding: 0 24px; height: 56px;
  background: var(--surface); border-bottom: 1px solid var(--gray-150);
}
.docs-brand { display: flex; align-items: center; gap: 10px; font-weight: 600; color: var(--gray-800); }
.docs-logo {
  width: 30px; height: 30px; border-radius: 8px;
  background: linear-gradient(135deg, var(--blue-500), var(--blue-700));
  color: #fff; font-size: 12px; font-weight: 700;
  display: flex; align-items: center; justify-content: center;
}
.docs-nav-links { margin-left: auto; display: flex; align-items: center; gap: 14px; font-size: 13px; }
.docs-wrap { max-width: 980px; margin: 0 auto; padding: 40px 24px 80px; }
.docs-hero h1 { font-size: 30px; margin: 0 0 10px; color: var(--gray-900); letter-spacing: -.01em; }
.docs-hero p { margin: 0 0 20px; color: var(--gray-500); max-width: 70ch; }
.docs-meta { display: grid; grid-template-columns: repeat(auto-fit, minmax(210px, 1fr)); gap: 10px; }
.docs-meta-item {
  border: 1px solid var(--gray-150); border-radius: var(--radius-md);
  background: var(--surface-2); padding: 10px 12px; font-size: 12.5px;
}
.docs-meta-item b { display: block; color: var(--gray-500); font-weight: 600; margin-bottom: 3px; font-size: 11px; text-transform: uppercase; letter-spacing: .04em; }
.docs-toc { margin: 28px 0 0; padding: 14px 18px; border-left: 3px solid var(--blue-200); background: var(--blue-50); border-radius: 0 var(--radius-md) var(--radius-md) 0; }
.docs-toc b { font-size: 12px; color: var(--gray-600); text-transform: uppercase; letter-spacing: .04em; }
.docs-toc ul { margin: 8px 0 0; padding-left: 18px; font-size: 13px; }
h2.docs-h2 { font-size: 20px; margin: 44px 0 14px; color: var(--gray-900); padding-bottom: 8px; border-bottom: 1px solid var(--gray-150); }
h3.docs-h3 { font-size: 15px; margin: 22px 0 6px; color: var(--gray-800); }
.docs-conv p { margin: 0 0 4px; font-size: 13.5px; color: var(--gray-600); }
.doc-ep { border: 1px solid var(--gray-150); border-radius: var(--radius-lg); padding: 16px 18px; margin: 0 0 14px; background: var(--surface); }
.doc-ep-head { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; margin-bottom: 8px; }
.doc-m { font-family: var(--mono); font-size: 11px; font-weight: 700; letter-spacing: .04em; padding: 3px 7px; border-radius: 5px; color: #fff; }
.doc-m.get { background: var(--blue-600); }
.doc-m.post { background: var(--green-600); }
.doc-m.delete { background: var(--red-500); }
.doc-path { font-family: var(--mono); font-size: 14px; font-weight: 600; color: var(--gray-900); }
.doc-tag { font-size: 11px; padding: 2px 8px; border-radius: 999px; border: 1px solid var(--gray-200); color: var(--gray-500); }
.doc-tag.admin { border-color: var(--amber-500); color: #92600a; background: var(--amber-50); }
.doc-ep h4 { margin: 0 0 6px; font-size: 14px; color: var(--gray-800); }
.doc-ep p.doc-d { margin: 0 0 10px; font-size: 13px; color: var(--gray-600); }
table.doc-t { width: 100%; border-collapse: collapse; font-size: 12.5px; margin: 0 0 10px; }
table.doc-t th { text-align: left; color: var(--gray-500); font-weight: 600; font-size: 11px; text-transform: uppercase; letter-spacing: .04em; padding: 6px 8px; border-bottom: 1px solid var(--gray-150); }
table.doc-t td { padding: 7px 8px; border-bottom: 1px solid var(--gray-100); vertical-align: top; color: var(--gray-600); }
table.doc-t td:first-child { font-family: var(--mono); color: var(--gray-800); white-space: nowrap; }
.doc-no-params { font-size: 12.5px; color: var(--gray-400); margin: 0 0 10px; }
.doc-label { font-size: 11px; text-transform: uppercase; letter-spacing: .04em; color: var(--gray-400); margin: 0 0 4px; }
pre.doc-pre { margin: 0; padding: 12px 14px; border-radius: var(--radius-md); background: var(--gray-50); border: 1px solid var(--gray-150); overflow-x: auto; font-family: var(--mono); font-size: 12px; line-height: 1.65; color: var(--gray-700); }
.docs-note { margin: 12px 0 0; padding: 10px 14px; border-radius: var(--radius-md); background: var(--amber-50); border: 1px solid var(--amber-500); font-size: 12.5px; color: var(--gray-700); }
.docs-foot { margin-top: 56px; padding-top: 18px; border-top: 1px solid var(--gray-150); font-size: 12px; color: var(--gray-400); display: flex; justify-content: space-between; gap: 12px; flex-wrap: wrap; }
@media (max-width: 640px) {
  .docs-nav { padding: 0 14px; }
  .docs-wrap { padding: 24px 14px 60px; }
  .docs-hero h1 { font-size: 24px; }
  .docs-nav-links { gap: 10px; font-size: 12px; }
}
"""


#: ``/privacy`` 等同类页面直接复用这套排版样式，避免各自维护一份（外观天然一致）。
SHARED_CSS = _CSS


def _esc(s: str) -> str:
    return (str(s).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


def _md(text: str) -> str:
    """极简行内标记：``code`` → <code>、**bold** → <b>（先转义，避免注入）。"""
    out = _esc(text)
    parts = out.split("``")
    if len(parts) > 1:
        out = "".join(
            p if i % 2 == 0 else f"<code>{p}</code>" for i, p in enumerate(parts)
        )
    while "**" in out:
        out = out.replace("**", "<b>", 1)
        if "**" in out:
            out = out.replace("**", "</b>", 1)
        else:
            break
    return out


def _params_table(params: list[dict], s: dict) -> str:
    if not params:
        return f'<p class="doc-no-params">{_esc(s["no.params"])}</p>'
    rows = []
    for p in params:
        desc_zh, desc_en = p["d"]  # type: ignore[misc]
        desc = desc_zh if s is _ZH else desc_en
        rows.append(
            "<tr><td>{n}</td><td>{t}</td><td>{r}</td><td>{d}</td></tr>".format(
                n=_esc(p["name"]), t=_esc(p["type"]),
                r=_esc(s["req.yes"] if p["required"] else s["req.no"]),
                d=_md(desc)))
    return (
        f'<table class="doc-t"><thead><tr><th>{_esc(s["th.param"])}</th>'
        f'<th>{_esc(s["th.type"])}</th><th>{_esc(s["th.req"])}</th>'
        f'<th>{_esc(s["th.desc"])}</th></tr></thead><tbody>'
        + "".join(rows) + "</tbody></table>")


def _endpoint_html(ep: dict, s: dict) -> str:
    title_zh, title_en = ep["title"]  # type: ignore[misc]
    desc_zh, desc_en = ep["desc"]  # type: ignore[misc]
    title = title_zh if s is _ZH else title_en
    desc = desc_zh if s is _ZH else desc_en
    method = str(ep["method"])
    badge = (f'<span class="doc-tag admin">{_esc(s["badge.admin"])}</span>'
             if ep["auth"] else f'<span class="doc-tag">{_esc(s["badge.public"])}</span>')
    parts = [
        '<article class="doc-ep">',
        '<div class="doc-ep-head">',
        f'<span class="doc-m {method.lower()}">{method}</span>',
        f'<code class="doc-path">{_esc(ep["path"])}</code>',
        badge,
        "</div>",
        f"<h4>{_esc(title)}</h4>",
        f'<p class="doc-d">{_md(desc)}</p>',
        _params_table(ep.get("params") or [], s),  # type: ignore[arg-type]
    ]
    body = ep.get("body")
    if body:
        body_zh, body_en = body  # type: ignore[misc]
        parts.append(f'<p class="doc-label">{_esc(s["label.body"])}</p>')
        parts.append(f'<pre class="doc-pre">{_esc(body_zh if s is _ZH else body_en)}</pre>')
    if ep.get("example"):
        parts.append(f'<p class="doc-label" style="margin-top:10px">{_esc(s["label.example"])}</p>')
        parts.append(f'<pre class="doc-pre">{_esc(str(ep["example"]))}</pre>')
    parts.append("</article>")
    return "".join(parts)


def _conventions_html(s: dict, anchor: str) -> str:
    blocks = ["conv.lang", "conv.id", "conv.unknown", "conv.err", "conv.sec", "conv.data"]
    out = [f'<h2 class="docs-h2" id="{anchor}">{_esc(s["sec.conv"])}</h2>',
           '<div class="docs-conv">']
    for key in blocks:
        out.append(f'<h3 class="docs-h3">{_md(s[key + ".h"])}</h3>')
        out.append(f"<p>{_md(s[key + '.b'])}</p>")
    out.append("</div>")
    return "".join(out)


def render(lang: str, base_url: str) -> str:
    """渲染整页 ``/docs`` HTML（``__HTML_LANG__`` / ``__ASSET_VER__`` 由 web 层替换）。"""
    s = _EN if lang == "en" else _ZH
    zh = s is _ZH
    other = "zh" if lang == "en" else "en"
    other_label = "中文" if lang == "en" else "EN"

    toc = ["<div class=\"docs-toc\"><b>{}</b><ul>".format(_esc(s["toc"]))]
    toc.append(f'<li><a href="#conventions">{_esc(s["sec.conv"])}</a></li>')
    toc.append('<li>{}</li>'.format(
        ", ".join(
            f'<a href="#g-{g}">{_esc(GROUPS[g][0] if zh else GROUPS[g][1])}</a>'
            for g in GROUPS if any(e["group"] == g for e in ENDPOINTS))))
    toc.append("</ul></div>")

    sections = []
    for g, (g_zh, g_en) in GROUPS.items():
        eps = [e for e in ENDPOINTS if e["group"] == g]
        if not eps:
            continue
        sections.append(
            f'<h2 class="docs-h2" id="g-{g}">{_esc(g_zh if zh else g_en)}</h2>')
        sections.extend(_endpoint_html(e, s) for e in eps)

    admin_note = (
        f'<p class="docs-note">{_md(s["admin.note"])}</p>'
        if any(e["auth"] for e in ENDPOINTS) else ""
    )

    return f"""<!DOCTYPE html>
<html lang="__HTML_LANG__">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{_esc(s["doc.title"])}</title>
<meta name="description" content="{_esc(s["doc.lead"])}">
<meta name="robots" content="index, follow">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="canonical" href="{_esc(base_url)}/docs">
<link rel="alternate" hreflang="en" href="{_esc(base_url)}/docs?lang=en">
<link rel="alternate" hreflang="zh-CN" href="{_esc(base_url)}/docs?lang=zh">
<link rel="alternate" hreflang="x-default" href="{_esc(base_url)}/docs">
<meta property="og:type" content="website">
<meta property="og:title" content="{_esc(s["doc.title"])}">
<meta property="og:description" content="{_esc(s["doc.lead"])}">
<meta property="og:image" content="{_esc(base_url)}/og-image.png">
<meta name="twitter:card" content="summary_large_image">
<link rel="stylesheet" href="/style.css?v=__ASSET_VER__">
<style>{_CSS}</style>
</head>
<body>
<a class="skip-link" href="#main">{_esc("跳到主内容" if zh else "Skip to content")}</a>
<nav class="docs-nav">
  <div class="docs-brand"><div class="docs-logo">AP</div>
    <span>{_esc("亚太统计分析系统" if zh else "Asia-Pacific Statistics")}</span></div>
  <div class="docs-nav-links">
    <a href="/">{_esc(s["back.home"])}</a>
    <a href="/app">{_esc(s["back.app"])}</a>
    <a href="/privacy">{_esc(s["privacy.link"])}</a>
    <a id="docsLangToggle" class="lang-toggle" href="/docs?lang={other}">{_esc(other_label)}</a>
  </div>
</nav>
<main class="docs-wrap" id="main">
  <div class="docs-hero">
    <h1>{_esc(s["doc.h1"])}</h1>
    <p>{_esc(s["doc.lead"])}</p>
    <div class="docs-meta">
      <div class="docs-meta-item"><b>{_esc(s["doc.base"])}</b>
        <code>{_esc(base_url)}</code><br><span style="color:var(--gray-400)">local: http://127.0.0.1:5000</span></div>
      <div class="docs-meta-item"><b>{_esc(s["doc.auth"])}</b>{_esc(s["doc.auth.v"])}</div>
      <div class="docs-meta-item"><b>{_esc(s["doc.format"])}</b>{_esc(s["doc.format.v"])}</div>
      <div class="docs-meta-item"><b>{_esc(s["doc.cache"])}</b>{_esc(s["doc.cache.v"])}</div>
    </div>
  </div>
  {''.join(toc)}
  {_conventions_html(s, "conventions")}
  <h2 class="docs-h2" id="endpoints">{_esc(s["sec.eps"])}</h2>
  {''.join(sections)}
  {admin_note}
  <div class="docs-foot">
    <span>{_esc(s["footer"])}</span>
    <span><a href="/privacy">{_esc(s["privacy.link"])}</a> ·
      GET /docs?lang={other} · <code>{_esc(base_url)}/sitemap.xml</code></span>
  </div>
</main>
</body>
</html>"""
